# Generated by Django 2.0.6 on 2018-06-12 05:57

import ckeditor.fields
import datetime
from django.conf import settings
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createDate', models.DateTimeField(default=datetime.datetime(2018, 6, 12, 5, 57, 20, 606469, tzinfo=utc))),
                ('updateDate', models.DateTimeField(default=datetime.datetime(2018, 6, 12, 5, 57, 20, 606469, tzinfo=utc))),
                ('name', models.CharField(default='', max_length=255)),
                ('parentId', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createDate', models.DateTimeField(default=datetime.datetime(2018, 6, 12, 5, 57, 20, 608970, tzinfo=utc))),
                ('updateDate', models.DateTimeField(default=datetime.datetime(2018, 6, 12, 5, 57, 20, 608970, tzinfo=utc))),
                ('parentId', models.IntegerField(null=True)),
                ('userId', models.IntegerField(null=True)),
                ('ip', models.CharField(max_length=255, null=True)),
                ('text', models.TextField(null=True)),
                ('status', models.IntegerField(default=1)),
                ('voteUp', models.IntegerField(default=0)),
                ('voteDown', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createDate', models.DateTimeField(default=datetime.datetime(2018, 6, 12, 5, 57, 20, 606969, tzinfo=utc))),
                ('updateDate', models.DateTimeField(default=datetime.datetime(2018, 6, 12, 5, 57, 20, 606969, tzinfo=utc))),
                ('name', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='blogspost',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='blogspost',
            name='commentCount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='blogspost',
            name='commentDate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='blogspost',
            name='createDate',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 12, 5, 57, 20, 607469, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='blogspost',
            name='keyWords',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='blogspost',
            name='status',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='blogspost',
            name='updateDate',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 12, 5, 57, 20, 607469, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='blogspost',
            name='user',
            field=models.ForeignKey(null=True, on_delete=None, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='blogspost',
            name='viewCount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='blogspost',
            name='voteDown',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='blogspost',
            name='voteUp',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='blogspost',
            name='body',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blogspost',
            name='title',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='content',
            field=models.ForeignKey(null=True, on_delete=None, to='blog.BlogsPost'),
        ),
        migrations.AddField(
            model_name='blogspost',
            name='category',
            field=models.ForeignKey(null=True, on_delete=None, to='blog.Category'),
        ),
        migrations.AddField(
            model_name='blogspost',
            name='tag',
            field=models.ForeignKey(null=True, on_delete=None, to='blog.Tag'),
        ),
    ]
