# Generated by Django 2.0.6 on 2018-06-12 06:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180612_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogspost',
            name='createDate',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 12, 6, 1, 28, 401766, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='blogspost',
            name='updateDate',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 12, 6, 1, 28, 402247, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='category',
            name='createDate',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 12, 6, 1, 28, 400266, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='category',
            name='updateDate',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 12, 6, 1, 28, 400749, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='createDate',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 12, 6, 1, 28, 403247, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='updateDate',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 12, 6, 1, 28, 403247, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tag',
            name='createDate',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 12, 6, 1, 28, 401265, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tag',
            name='updateDate',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 12, 6, 1, 28, 401766, tzinfo=utc)),
        ),
    ]
